server:
  port: 8081
spring:
  sql:
    init:
      mode: always
  flyway:
    locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:dev}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:tripro123}
    driverClassName: com.mysql.cj.jdbc.Driver

