name: ci

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '11.0.8'
      - name: Build with Maven
        run: mvn clean install
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: trivip002
          password: 5419e1a3-a9dd-4f73-9488-8e692b2ea2e2 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: trivip002/database:latest
