name: ci

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 17
          maven-version: 3.8.4
          
      - name: Build with Maven
        run: mvn clean install
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: trivip002
          password: 5419e1a3-a9dd-4f73-9488-8e692b2ea2e2 
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: trivip002/database:latest
